#!/usr/bin/env bash
set -ex

source routing-ci/scripts/script_helpers.sh

CF_APP_DOMAIN="${ENVIRONMENT}.${SYSTEM_DOMAIN}"
CF_API="api.${CF_APP_DOMAIN}"

if [[ ${CF_SKIP_SSL_VALIDATION} == 'true' ]];
then
  cf api ${CF_API} --skip-ssl-validation
else
  cf api ${CF_API}
fi

echo "Authenticating with CF"

set +x
  bosh_login "${ENVIRONMENT}"
set -x

set +x
  if [[ -z ${CF_USERNAME} && -z ${CF_PASSWORD} ]]; then
    set_username_password
  fi
set -x

set +x
  cf auth ${CF_USERNAME} ${CF_PASSWORD}
set -x

cf target -o ${CF_ORG} -s ${CF_SPACE}

TCP_DOMAIN=tcp.${CF_APP_DOMAIN}
TCP_PORT=$(cf routes | grep ${TCP_DOMAIN}| awk '{print $3}')

echo "Starting zero downtime test..."
APP_URL="http://${CF_APP_NAME}.${CF_APP_DOMAIN}"
POLL_URL="${TCP_DOMAIN}:${TCP_PORT}"

curl $APP_URL/start -X POST -d'{"Endpoint":"'${POLL_URL}'"}'
