#!/bin/bash
set -exuo pipefail


cp deployments-routing/routing-release-private.yml routing-release/config/private.yml

pushd routing-release
  bosh vendor-package golang-1.9-linux ../golang-release
popd

shopt -s dotglob
cp -R routing-release/* modified-routing-release/
