#!/bin/bash

set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

ENVIRONMENT_DIR=$PWD/deployments-routing/
STEMCELL_PATH=$(ls $STEMCELL_REGEX)

pushd "${ENVIRONMENT_DIR}"
  source ./scripts/script_helpers.sh
  bosh_login "${ENVIRONMENT}"
popd

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

BOSH_DEPLOYMENT="${DEPLOYMENT:-$BOSH_DEPLOYMENT}"

bosh -n us "${STEMCELL_PATH}"

IFS=', ' read -r -a array <<< "${RELEASES_DIR}"

for element in "${array[@]}"
do
  RELEASE_PATH=$(ls $element)
  bosh -n ur "${RELEASE_PATH}"
done

bosh -n -e "${ENVIRONMENT}" deploy "${MANIFEST}"

echo "Running cipher test suite"
bosh run-errand run-cipher-test --keep-alive --download-logs
