#!/bin/bash
set -e -x

source ~/.bashrc
source "${PWD}/deployments-routing/scripts/script_helpers.sh"

if [ -n "${LOGS_DIR}" ]; then
  mkdir "${LOGS_DIR}"
fi

STEMCELL_PATH="$(ls ${STEMCELL_REGEX})"

set +x
bosh_login "${ENVIRONMENT}"
set -x

export BOSH_DEPLOYMENT="${DEPLOYMENT:-cf}"
bosh -n upload-stemcell "${STEMCELL_PATH}"

IFS=', ' read -r -a array <<< "${RELEASES_DIR}"

for element in ${array[@]}
do
  RELEASE_PATH="$(ls "${element}")"
  bosh -n upload-release "${RELEASE_PATH}"
done

bosh -n deploy "${MANIFEST}"
