#!/bin/bash
set -exuo pipefail


cp deployments-routing/routing-release-private.yml routing-release/config/private.yml

pushd routing-release
  bosh vendor-package ${PACKAGE} ../package-release
popd

pushd routing-release
  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"

  git checkout "${BRANCH}"

  if [[ -n $(git status --porcelain) ]]; then
    echo "changes detected, will commit..."
    git add --all
    git commit -m "Upgrade ${PACKAGE} in routing-release"

    git log -1 --color | cat
  else
   echo "no changes in repo, no commit necessary"
  fi
popd

shopt -s dotglob
cp -R routing-release/* modified-routing-release/
