#!/bin/bash

set -e -x -u

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

root_dir="${PWD}"
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

export RTR_VERSION=$(cat version/version)

pushd $CF_ROUTING_RELEASE_DIR/

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

	pushd src/code.cloudfoundry.org/routing-api-cli
		git checkout master
		git pull origin master
		./bin/build-all.sh

		pushd out
			tar -vczf rtr-darwin-amd64.tgz rtr-darwin-amd64
			tar -vczf rtr-linux-amd64.tgz rtr-linux-amd64
			echo "===GENERATED BINARIES==="
			CLI_BINARY=$PWD
		popd

		ls out/

	popd
popd

mkdir -p $OUTPUT_DIR

cp -r $CLI_BINARY $OUTPUT_DIR
ls $OUTPUT_DIR
