#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Inputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

main() {

  echo "instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: run_cipher_test
    properties:
      router:
        ciphers: ${CIPHERS}
        ip: 10.0.16.12
        port: 443
    release: cipher-test
  lifecycle: errand
  name: run-cipher-test
  networks:
  - name: default
  stemcell: trusty
  vm_type: default
name: cipher
releases:
- name: cipher-test
  version: latest
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000" > $OUTPUT_DIR/cipher.yml
}

main
