#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -ue
set -o pipefail

root_dir="${PWD}"

# Inputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

ENVIRONMENT_DIR=$PWD/deployments-routing/${ENVIRONMENT}

set +x
pushd $ENVIRONMENT_DIR
	BOSH_CA_CERT="$(bbl director-ca-cert)"
	export BOSH_CA_CERT
	BOSH_ENVIRONMENT=$(bbl director-address)
	export BOSH_ENVIRONMENT
	BOSH_CLIENT=$(bbl director-username)
	export BOSH_CLIENT
	BOSH_CLIENT_SECRET=$(bbl director-password)
	export BOSH_CLIENT_SECRET
popd
set -x
FIRST_ROUTER_IP=$(bosh2 -d cf vms | grep ^router/ | awk '{print $4}' | head -n1)

main() {

  echo "instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: run_cipher_test
    properties:
      router:
        ciphers: ${CIPHERS}
        ip: ${FIRST_ROUTER_IP}
        port: 443
    release: cipher-test
  lifecycle: errand
  name: run-cipher-test
  networks:
  - name: default
  stemcell: trusty
  vm_type: default
name: cipher
releases:
- name: cipher-test
  version: latest
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000" > "$OUTPUT_DIR/cipher.yml"
}

main
