#!/bin/bash
set -e -x

source ~/.bashrc
source "${PWD}/deployments-routing/scripts/script_helpers.sh"

if [ -n "${LOGS_DIR}" ]; then
  mkdir "${LOGS_DIR}"
fi

num_runs="${NUMBER_OF_RUNS:-1}"

bosh_login "${ENVIRONMENT}"
export BOSH_DEPLOYMENT="${DEPLOYMENT:-cf}"

for ((i=0; i<${num_runs}; i++)); do
    echo "Starting run ${i}"
    bosh "${COMMAND}"
    echo "Finished run ${i}"
done
