#!/bin/bash
set -e -x

source ~/.bashrc

if [ -n "$LOGS_DIR" ]; then
  mkdir $LOGS_DIR
fi

ENVIRONMENT_DIR=$PWD/deployments-routing/${ENVIRONMENT}

num_runs=${NUMBER_OF_RUNS:-1}

set +x
pushd $ENVIRONMENT_DIR
  eval "$(bbl print-env)"
popd
set -x


for ((i=0; i<${num_runs}; i++)); do
    echo "Starting run ${i}"
    bosh -e $BOSH_ENVIRONMENT -d $BOSH_DEPLOYMENT $COMMAND
    echo "Finished run ${i}"
done
