#!/bin/bash
set -euo pipefail

FORMATTED_KEY="$(sed 's/^/      /' <(echo $GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY))"
cat > $PWD/istio-release/config/private.yml <<EOF
---
blobstore:
  options:
    credentials_source: static
    json_key: |
$FORMATTED_KEY
EOF


pushd istio-release
  bosh add-blob ../grpcurl-bin/grpcurl grpcurl-linux/grpcurl
  bosh upload-blobs
  bosh blobs
  git --no-pager diff config/ packages/
  git add config/blobs.yml packages/grpcurl
  git config user.email "cf-routing-eng@pivotal.io"
  git config user.name "Routing CI (Automated)"
  git commit -m "Update grpcurl blob"
  cp -a ./ ../updated-istio-release/
popd
