#!/bin/bash -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function bosh_upload_nats_release() {
  pushd nats-release
    bosh create-release --force
    bosh upload-release
  popd
}

function bosh_deploy_nats() {
  pushd stemcell
    bosh upload-stemcell stemcell.tgz
  popd

  pushd nats-release
    bosh \
      -n \
      -d "nats" \
      deploy "${PWD}/example-manifests/nats.yml" \
      --vars-store vars.yml \
      -o create-nats-dev-release.yml
  popd
}

function main() {
  setup_bosh_env_vars
  bosh_upload_nats_release
  bosh_deploy_nats
}

trap close_bbl_ssh_connection EXIT

main
