#!/bin/bash
set -exuo pipefail


cp deployments-routing/${RELEASE}-private.yml release/config/private.yml

pushd release
  bosh vendor-package ${PACKAGE} ../package-release

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"

  git checkout "${BRANCH}"

  if [[ -n $(git status --porcelain) ]]; then
    echo "changes detected, will commit..."
    git add --all
    git commit -m "Upgrade ${PACKAGE} in ${RELEASE}"

    git log -1 --color | cat
  else
   echo "no changes in repo, no commit necessary"
  fi
popd

shopt -s dotglob
cp -R release/* modified-release/
