#!/bin/bash

set -e -x -u

cp -r cf-deployment/* modified-cf-deployment
cp -r routing-ci/operations/* modified-cf-deployment/operations/
cp -r deployments-routing/${ENVIRONMENT}/operations/ modified-cf-deployment/operations/
