#!/bin/bash
set -exu
set -o pipefail

if [ -z "$SUBMODULE_PATH" ]; then
  echo "SUBMODULE_PATH has not been set"
  exit 1
fi

submodule_log () {
  git submodule foreach --quiet 'echo bump $name'
  echo
  git diff --cached --submodule
}


# discover the SHA that we want to bump to
pushd submodule-latest
  SHA="$(git rev-parse HEAD)"
  REMOTE=$PWD
popd


pushd needs-bump
  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"

  git checkout "${BRANCH}"
  pushd "${SUBMODULE_PATH}"
    git remote add local "${REMOTE}"
    git fetch local
    git checkout "${SHA}"
  popd
  git add .
  git commit -m "$( submodule_log )"
popd
git clone needs-bump bumped
cd bumped
git log -1 --color | cat
