#!/bin/bash
set -e -x -u -o pipefail

indir=./env-repo
outdir=./modified-env-repo
git clone "${indir}" "${outdir}"

modified_bbl_state_dir="${outdir}/${BBL_STATE_DIR}"
mkdir -p "${modified_bbl_state_dir}"

cp -r "plan-patches/${PLAN_PATCH_DIR}" "${modified_bbl_state_dir}"

function set_git_config() {
  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function commit {
  local git_root_dir
  git_root_dir="${1}"
  local commit_message
  commit_message="${2}"

  pushd "${git_root_dir}"
    if [[ -n $(git status --porcelain) ]]; then
    set_git_config
    git add .
    git commit -m "${commit_message}"
  fi
}

commit "${outdir}" "${GIT_COMMIT_MSG}"
