#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"

pushd deployments-routing
  source ./scripts/script_helpers.sh
  bosh_login "${ENVIRONMENT}"
popd

bosh2 -e "${ENVIRONMENT}" ur "${CF_ROUTING_RELEASE_TARBALL_DIR}"/*.tgz

bosh2 -e "${ENVIRONMENT}" -d cf-warden manifest > /tmp/cf.yml
CF_RELEASE_MANIFEST=/tmp/cf.yml

bosh2 -e "${ENVIRONMENT}" -d cf-warden-diego manifest > /tmp/diego.yml
DIEGO_RELEASE_MANIFEST=/tmp/diego.yml


pushd "${CF_ROUTING_RELEASE_DIR}"
  mkdir -p bosh-lite/deployments
  DIRECTOR_UUID=$(bosh2 -e "${ENVIRONMENT}" env --json | jq .Tables[0].Rows[0].uuid) \
  ./scripts/generate-manifest \
  -c "${CF_RELEASE_MANIFEST}" \
  -d "${DIEGO_RELEASE_MANIFEST}" \
  -l bosh-lite/stubs/property-overrides.yml \
  -l bosh-lite/stubs/instance-count-overrides.yml \
  -l bosh-lite/stubs/persistent-disk-overrides.yml \
  -l "../deployments-routing/${ENVIRONMENT}/stubs/routing/iaas-settings.yml" \
  > bosh-lite/deployments/routing.yml
popd

bosh2 -n -e "${ENVIRONMENT}" -d cf-warden-routing deploy routing-release/bosh-lite/deployments/routing.yml

# redeploy CF release
pushd "${CF_RELEASE_DIR}"
  spiff merge /tmp/cf.yml \
  ../routing-release/bosh-lite/stubs/cf/routing-and-diego-enabled-overrides.yml \
  > /tmp/cf-updated.yml
popd

bosh2 -n -e "${ENVIRONMENT}" -d cf-warden deploy /tmp/cf-updated.yml

bosh2 -e "${ENVIRONMENT}" -d cf-warden-routing run-errand routing_acceptance_tests --keep-alive --download-logs
bosh2 -e "${ENVIRONMENT}" -d cf-warden-routing run-errand routing_smoke_tests --keep-alive --download-logs
