#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"

pushd deployments-routing
 ./scripts/bosh-login "${ENVIRONMENT}"
popd

bosh2 -e "${ENVIRONMENT}" ur "${CF_RELEASE_TARBALL_DIR}"/cf-*.tgz

pushd "${CF_RELEASE_DIR}"
  mkdir -p bosh-lite/deployments
  DIRECTOR_UUID=$(bosh2 -e "${ENVIRONMENT}" env --json | jq .Tables[0].Rows[0].uuid)
  ./scripts/generate_deployment_manifest \
  bosh-lite \
  <(echo "director_uuid: ${DIRECTOR_UUID}") \
  ../deployments-routing/"${ENVIRONMENT}"/stubs/**/*.yml \
  > bosh-lite/deployments/cf.yml

  bosh2 -n -e "${ENVIRONMENT}" -d cf-warden deploy bosh-lite/deployments/cf.yml
popd
