#!/bin/bash
set -ex -o pipefail

source routing-ci/scripts/script_helpers.sh

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
bosh_login "${ENVIRONMENT}"

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

ENVIRONMENT_DIR="${PWD}/deployments-routing/"

pushd zero-downtime-release
    bosh create-release
    bosh -e "${ENVIRONMENT}" ur --rebase
    bosh -e "${ENVIRONMENT}" -d zero-downtime -n deploy "${ENVIRONMENT_DIR}/${ENVIRONMENT}/zero_downtime/zero_downtime.yml" --no-redact
popd
