#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

ENVIRONMENT_DIR="${PWD}/deployments-routing/"

pushd "${ENVIRONMENT_DIR}"
  source ./scripts/script_helpers.sh
  bosh_login "${ENVIRONMENT}"
popd

pushd zero-downtime-release
    bosh create-release
    bosh -e "${ENVIRONMENT}" ur --rebase
    bosh -e "${ENVIRONMENT}" -d zero-downtime -n deploy "${ENVIRONMENT_DIR}/${ENVIRONMENT}/zero_downtime/zero_downtime.yml" --no-redact
popd
