#!/bin/bash

set -e -u
set -o pipefail

extract_var()
{
  local workspace="${HOME}/workspace"
  if [[ ! -d "${workspace}" ]]; then
    workspace="${HOME}"
  fi

  env=$1
  var=$2
  local env_root="${workspace}/deployments-routing/${env}"
  local deployment_vars_file="${env_root}/deployment-vars.yml"

  if [[ -f "${deployment_vars_file}" ]]; then
    bosh int --path /"${var}" "${deployment_vars_file}"
  else
    pushd "${env_root}/bbl-state" > /dev/null
      eval "$(bbl print-env)"
    popd > /dev/null
    credhub find -j -n "${var}" | jq -r .credentials[].name | xargs credhub get -j -n | jq -r .value
  fi
}

get_system_domain()
{
  local env
  env=$1
  if [ "$env" = "lite" ]; then
    echo "bosh-lite.com"
    return
  fi

  echo "${env}.routing.cf-app.com"
}

env=$1
cf api "api.$(get_system_domain "$env")" --skip-ssl-validation
cf auth admin "$(extract_var "$env" cf_admin_password)"
