#!/bin/bash

set -e -u
set -o pipefail

extract_var()
{
  env=$1
  var=$2
  bosh int --path /$var ${HOME}/workspace/deployments-routing/$env/deployment-vars.yml
}

get_system_domain()
{
  local env
  env=$1
  if [ "$env" = "lite" ]; then
    echo "bosh-lite.com"
    return
  fi

  local system_domain
  system_domain=$(extract_var "${env}" system_domain 2>/dev/null)
  if [[ $? -ne 0 ]]; then
    system_domain="${env}".routing.cf-app.com
  fi

  echo "${system_domain}"
}

cf_target()
{
  env=$1

  cf api "api.$(get_system_domain $env)" --skip-ssl-validation
  cf auth admin "$(extract_var $env cf_admin_password)"
}

cf_target "$1"
