#!/bin/bash

set -e -u
set -o pipefail

env_dir=${HOME}/workspace/deployments-routing/lite
cf_deployment_dir=${HOME}/workspace/cf-deployment
bosh_deployment_dir=${HOME}/workspace/bosh-deployment

bosh create-env ${bosh_deployment_dir}/bosh.yml \
--state $env_dir/state.json \
-o ${bosh_deployment_dir}/virtualbox/cpi.yml \
-o ${bosh_deployment_dir}/virtualbox/outbound-network.yml \
-o ${bosh_deployment_dir}/bosh-lite.yml \
-o ${bosh_deployment_dir}/bosh-lite-runc.yml \
-o ${bosh_deployment_dir}/jumpbox-user.yml \
-o ${bosh_deployment_dir}/local-dns.yml \
--vars-store $env_dir/bosh-vars.yml \
-v director_name="Bosh Lite Director" \
-v internal_ip=192.168.50.6 \
-v internal_gw=192.168.50.1 \
-v internal_cidr=192.168.50.0/24 \
-v outbound_network_name="NatNetwork"

bosh -e 192.168.50.6 --ca-cert <(bosh int $env_dir/bosh-vars.yml --path /director_ssl/ca) alias-env vbox
BOSH_CLIENT="admin"
BOSH_CLIENT_SECRET="$(bosh int $env_dir/bosh-vars.yml --path /admin_password)"
BOSH_ENVIRONMENT="vbox"
BOSH_DEPLOYMENT="cf"
BOSH_CA_CERT="$(bosh int $env_dir/bosh-vars.yml --path /director_ssl/ca)"

export BOSH_CLIENT
export BOSH_CLIENT_SECRET
export BOSH_ENVIRONMENT
export BOSH_DEPLOYMENT
export BOSH_CA_CERT

STEMCELL_VERSION="$(bosh int ${cf_deployment_dir}/cf-deployment.yml --path=/stemcells/0/version)"
echo "will upload stemcell ${STEMCELL_VERSION}"
bosh -e vbox upload-stemcell "https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=${STEMCELL_VERSION}"

bosh -e vbox -n update-cloud-config "${cf_deployment_dir}/iaas-support/bosh-lite/cloud-config.yml"

# mac specific
sudo route add -net "10.244.0.0/16" "192.168.50.6"
