#!/bin/bash

set -e -u
set -o pipefail

env_dir=${HOME}/workspace/deployments-routing/lite
bosh_deployment_dir=${HOME}/workspace/bosh-deployment

bosh delete-env ${bosh_deployment_dir}/bosh.yml \
--state $env_dir/state.json \
-o ${bosh_deployment_dir}/virtualbox/cpi.yml \
-o ${bosh_deployment_dir}/virtualbox/outbound-network.yml \
-o ${bosh_deployment_dir}/bosh-lite.yml \
-o ${bosh_deployment_dir}/bosh-lite-runc.yml \
-o ${bosh_deployment_dir}/jumpbox-user.yml \
-o ${bosh_deployment_dir}/local-dns.yml \
--vars-store $env_dir/bosh-vars.yml \
-v director_name="Bosh Lite Director" \
-v internal_ip=192.168.50.6 \
-v internal_gw=192.168.50.1 \
-v internal_cidr=192.168.50.0/24 \
-v outbound_network_name="NatNetwork"
