#!/bin/bash

set -e -u
set -o pipefail

env_dir=${HOME}/workspace/deployments-routing/lite
cf_deployment_dir=${HOME}/workspace/cf-deployment
mkdir -p $env_dir/extra-ops-files

extra_ops_files=""

shopt -s nullglob
pushd $env_dir/extra-ops-files
  for op in $env_dir/extra-ops-files/*.yml
  do
    extra_ops_files="${extra_ops_files} -o $op"
  done
popd

bosh deploy --no-redact ${cf_deployment_dir}/cf-deployment.yml \
-o ${cf_deployment_dir}/operations/use-compiled-releases.yml \
-o ${cf_deployment_dir}/operations/bosh-lite.yml \
$extra_ops_files \
--vars-store $env_dir/deployment-vars.yml \
-v system_domain=bosh-lite.com
