#!/bin/bash
set -euo pipefail

cat > $PWD/istio-release/config/private.yml <<EOF
---
blobstore:
  options:
    secret_access_key: ${AWS_BLOBSTORE_SECRET_ACCESS_KEY}
    access_key_id: ${AWS_BLOBSTORE_ACCESS_KEY_ID}
EOF

new_envoy_version="$(cat envoy-tarball/version)"
pushd istio-release
  bosh2 sync-blobs
  old_envoy_version=$(ls -1 blobs/envoy-linux/envoy*.tgz | xargs basename | sed 's/envoy-\(.*\).tgz/\1/g')

  bosh2 remove-blob envoy-linux/envoy-${old_envoy_version}.tgz
  bosh2 add-blob ../envoy-tarball/envoy.tgz envoy-linux/envoy-${new_envoy_version}.tgz
  sed -i "s/envoy-linux\/envoy.*\.tgz/envoy-linux\/envoy-${new_envoy_version}\.tgz/g" packages/envoy/*
  bosh2 blobs
  bosh2 upload-blobs
  bosh2 blobs
  git --no-pager diff config/ packages/
  git add config/blobs.yml packages/envoy
  git config user.email "cf-routing-eng@pivotal.io"
  git config user.name "Routing CI (Automated)"
  git commit -m "Update envoy blob to ${new_envoy_version}"
  cp -a ./ ../updated-istio-release/
popd
