#!/bin/bash
set -e -x -u -o pipefail

indir=./modified-deployments-routing
outdir=./env-repo
git clone "${indir}" "${outdir}"

cp -r "${PWD}/routing-ci/add-stubs/stub-ops" "${outdir}/${ENVIRONMENT}/"
cp -r "${PWD}/routing-ci/add-stubs/stubs" "${outdir}/${ENVIRONMENT}/"

domain_stub="${outdir}/${ENVIRONMENT}/stubs/cf/domain.yml"
updated_domain_stub="$(bosh int "${domain_stub}" -v system_domain="${ENVIRONMENT}.routing.cf-app.com")"
echo "${updated_domain_stub}" > "${domain_stub}"

admin_password_stub="${outdir}/${ENVIRONMENT}/stubs/cf/admin_password.yml"
updated_admin_password_stub="$(bosh int "${admin_password_stub}" \
  --vars-file="${outdir}/pipelines/shared-credentials.yml")"
echo "${updated_admin_password_stub}" > "${admin_password_stub}"

consul_certs_stub="${outdir}/${ENVIRONMENT}/stubs/cf/consul_certs.yml"
updated_consul_certs_stub="$(bosh int "${consul_certs_stub}" \
  --vars-file="${outdir}/pipelines/shared-credentials.yml")"
echo "${updated_consul_certs_stub}" > "${consul_certs_stub}"

router_ssl_stub="${outdir}/${ENVIRONMENT}/stubs/cf/router-ssl.yml"
updated_router_ssl_stub="$(bosh int "${router_ssl_stub}" \
  --vars-file="${outdir}/pipelines/shared-credentials.yml")"
echo "${updated_router_ssl_stub}" > "${router_ssl_stub}"

function set_git_config() {
  if [ -z "${GIT_COMMIT_USERNAME}" ]; then
    GIT_COMMIT_USERNAME="CI Bot"
  fi

  if [ -z "${GIT_COMMIT_EMAIL}" ]; then
    GIT_COMMIT_EMAIL="cf-release-integration@pivotal.io"
  fi

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"
}

function commit_stubs {
  local root_dir
  root_dir="${1}"
  local commit_message
  commit_message="${2}"

  pushd "${root_dir}/env-repo"
    if [[ -n $(git status --porcelain) ]]; then
    set_git_config
    git add stubs stub-ops
    git commit -m "${commit_message}"
  fi
}

commit_stubs "${PWD}" "Adding stubs"
