#!/bin/bash
set -eu -o pipefail

: "${SSH_DESTINATION_CIDR:="10.0.0.0/8"}"

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"

export GOPATH="${PWD}"
export PATH="${PATH}:${GOPATH}/bin"

CF_VARS_STORE_PATH="$PWD/deployments-routing/${ENVIRONMENT}/deployment-vars.yml"
export CF_VARS_STORE_PATH

BBL_STATE="$PWD/deployments-routing/${ENVIRONMENT}/bbl-state"

pushd bbr-binary-release
  tar xvf ./*.tar
  build_path="$(pwd)/releases/bbr"
  export BBR_BUILD_PATH=${build_path}
popd

rm -f ~/.gitconfig

cleanup() {
  kill "${tunnel_pid}"
}
trap 'cleanup' EXIT

pushd "src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests" > /dev/null
  ./scripts/run_acceptance_tests_with_bbl_env.sh "$BBL_STATE"
popd > /dev/null
