#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"

pushd deployments-routing
 ./scripts/bosh-login "${ENVIRONMENT}"
popd

bosh2 -e "${ENVIRONMENT}" ur "${DIEGO_RELEASE_TARBALL_DIR}/garden-runc-*.tgz"
bosh2 -e "${ENVIRONMENT}" ur "${DIEGO_RELEASE_TARBALL_DIR}/cflinuxfs2-*.tgz"
bosh2 -e "${ENVIRONMENT}" ur "${DIEGO_RELEASE_TARBALL_DIR}/diego-*.tgz"


bosh2 -e "${ENVIRONMENT}" -d cf-warden manifest > /tmp/cf.yml
CF_RELEASE_MANIFEST=/tmp/cf.yml


pushd "${DIEGO_RELEASE_DIR}"
  mkdir -p bosh-lite/deployments
  ./scripts/generate-deployment-manifest \
  -c "${CF_RELEASE_MANIFEST}" \
  -i manifest-generation/bosh-lite-stubs/iaas-settings.yml \
  -p manifest-generation/bosh-lite-stubs/property-overrides.yml \
  -n manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
  -x \
  -Q \
  -s manifest-generation/bosh-lite-stubs/postgres/diego-sql.yml \
  -v manifest-generation/bosh-lite-stubs/release-versions.yml \
  > bosh-lite/deployments/diego.yml
popd

bosh2 -n -e "${ENVIRONMENT}" -d cf-warden-diego deploy diego-release-src/bosh-lite/deployments/diego.yml
