#!/bin/bash
set -exu -o pipefail

source routing-ci/scripts/script_helpers.sh

ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
bosh_login "${ENVIRONMENT}"

function cleanup() {
  pkill ssh || true
}
trap 'cleanup' EXIT

pushd "${PWD}/deployments-routing"
    set +x
    cmd='sudo chmod a+w /var/vcap/store/syslog_storer/syslog.log; tail -n 100 /var/vcap/store/syslog_storer/syslog.log > /var/vcap/store/syslog_storer/syslog.log'
    bosh ssh -c "$cmd" syslog_storer
    sleep 30
    bosh scp syslog_storer:/var/vcap/store/syslog_storer/syslog.log .
    set -x
    grep "$(date -u +%Y-%m-%dT)$(($(date -u +%H)-1))\|$(date -u +%Y-%m-%dT%H)" syslog.log | grep -m 1 "vcap.routing_api.stdout"
    grep "$(date -u +%Y-%m-%dT)$(($(date -u +%H)-1))\|$(date -u +%Y-%m-%dT%H)" syslog.log | grep -m 1 "vcap.gorouter.stdout"
    grep "$(date -u +%Y-%m-%dT)$(($(date -u +%H)-1))\|$(date -u +%Y-%m-%dT%H)" syslog.log | grep -m 1 "vcap.tcp_router.stdout"
popd
