#!/usr/bin/env bash
set -ex

source routing-ci/scripts/script_helpers.sh

CF_APP_DOMAIN="${ENVIRONMENT}.${SYSTEM_DOMAIN}"
CF_API="api.${CF_APP_DOMAIN}"
if [[ "${CF_SKIP_SSL_VALIDATION}" == 'true' ]];
then
  cf api "${CF_API}" --skip-ssl-validation
else
  cf api "${CF_API}"
fi

echo "Authenticating with CF"

set +x
  bosh_login "${ENVIRONMENT}"
set -x

set +x
  if [[ -z ${CF_USERNAME} && -z ${CF_PASSWORD} ]]; then
    set_username_password
  fi
set -x

set +x
  cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
set -x

cf target -o "${CF_ORG}" -s "${CF_SPACE}"

# Expects the app to be already present
cf apps | grep "${CF_APP_POLL_NAME}"

echo "Starting zero downtime test..."

POLL_URL="http://${CF_POLL_APP_NAME}.${CF_APP_DOMAIN}/health"
APP_URL="http://${CF_APP_NAME}.${CF_APP_DOMAIN}"

curl "${APP_URL}"/start -X POST -d'{"Endpoint":"'${POLL_URL}'"}'
