#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

if [ "${CF_SKIP_SSL_VALIDATION}" == 'true' ] ;
then
  cf api "${CF_API}" --skip-ssl-validation
else
  cf api "${CF_API}"
fi

echo "Authenticating with CF"

ENV_ROOT="${PWD}/deployments-routing/${ENVIRONMENT}"

pushd "${ENV_ROOT}/bbl-state" > /dev/null
  set +x
    eval "$(bbl print-env)"
  set -x
popd

set +x
  if [[ -z ${CF_USERNAME} && -z ${CF_PASSWORD} ]]; then
    json_output=$(credhub get -n /jubilee/cf-user -j)
    ${CF_USERNAME}="$(${json_output} | jq .values.username)"
    ${CF_PASSWORD}="$(${json_output} | jq .values.password)"
  fi
set -x

set +x
  cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
set -x

cf target -o "${CF_ORG}" -s "${CF_SPACE}"

# Expects the app to be already present
cf apps | grep "${CF_APP_POLL_NAME}"

echo "Starting zero downtime test..."

POLL_URL="http://${CF_POLL_APP_NAME}.${CF_APP_DOMAIN}/health"
APP_URL="http://${CF_APP_NAME}.${CF_APP_DOMAIN}"

curl "${APP_URL}"/start -X POST -d'{"Endpoint":"'${POLL_URL}'"}'
