#!/bin/bash

set -ex
 # Cannot set -u before sourcing .bashrc because of all
 # the unbound variables in things beyond our control.
 source ~/.bashrc

 if [ ${CF_SKIP_SSL_VALIDATION} == 'true' ] ;
 then
   cf api ${CF_API} --skip-ssl-validation
 else
   cf api ${CF_API}
 fi

 cf auth ${CF_ADMIN_USER} ${CF_ADMIN_PASSWORD}
 cf create-org ${CF_ORG}
 cf target -o ${CF_ORG}
 cf create-space ${CF_SPACE}
 cf target -o ${CF_ORG} -s ${CF_SPACE}
 cf create-user ${CF_USERNAME} ${CF_PASSWORD}
 cf set-space-role ${CF_USERNAME} ${CF_ORG} ${CF_SPACE} ${CF_SPACE_ROLE}
