#!/usr/bin/env bash
set -ex

source routing-ci/scripts/script_helpers.sh

CF_API="api.${ENVIRONMENT}.${SYSTEM_DOMAIN}"

if [[ "${CF_SKIP_SSL_VALIDATION}" == 'true' ]];
then
  cf api "${CF_API}" --skip-ssl-validation
else
  cf api "${CF_API}"
fi

set +x
  bosh_login "${ENVIRONMENT}"
set -x

set +x
  if [[ -z ${CF_USERNAME} && -z ${CF_PASSWORD} ]]; then
    set_username_password
  fi
set -x

set +x
  cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
set -x

cf target -o "${CF_ORG}" -s "${CF_SPACE}"

echo "Cloning doctorroute repo"
git clone https://github.com/cf-routing/doctorroute.git

pushd doctorroute
	set +e
	cf apps | grep "${CF_APP_NAME}" | grep "started"
	EXIT_STATUS=$?
	set -e
  # If app does not exist push and map-route
	if [ "${EXIT_STATUS}" != "0" ]; then
	    echo "Pushing doctorroute..."
	    cf target -o "${CF_ORG}" -s "${CF_SPACE}"
	    cf push "${CF_APP_NAME}" -d "${CF_APP_DOMAIN}" --random-route
	    cf map-route "${CF_APP_NAME}" "${CF_APP_DOMAIN}" -n "${CF_APP_NAME}"
	fi
popd
