#!/bin/bash
set -exuo pipefail

set +x
if [[ -z "${GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY}" ]]; then
cat > ${PWD}/${RELEASE}/config/private.yml <<EOF
---
blobstore:
  options:
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
EOF
fi

if [[ -z ${AWS_ACCESS_KEY_ID} ]]; then
FORMATTED_KEY="$(sed 's/^/      /' <(echo ${GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY}))"
cat > ${PWD}/${RELEASE}/config/private.yml <<EOF
---
blobstore:
  options:
    credentials_source: static
    json_key: |
${FORMATTED_KEY}
EOF
fi
set -x

pushd release
  bosh vendor-package "${PACKAGE}" ../package-release

  bosh create-release --tarball=/tmp/release.tgz

  version=$(cat /tmp/release.tgz | tar -Oxz packages/golang-1-linux.tgz | tar z --list | grep -ohE "go[0-9]\.[0-9]{1,2}\.[0-9]{1,2}")

  git config user.name "${GIT_COMMIT_USERNAME}"
  git config user.email "${GIT_COMMIT_EMAIL}"

  git checkout "${BRANCH}"

  if [[ -n $(git status --porcelain) ]]; then
    echo "changes detected, will commit..."
    git add --all
    git commit -m "Upgrade ${PACKAGE} to ${version} in ${RELEASE}"

    git log -1 --color | cat
  else
   echo "no changes in repo, no commit necessary"
  fi
popd

shopt -s dotglob
cp -R release/* modified-release/
